// <auto-generated />
using System;
using Family_Meetup.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Family_Meetup.Migrations
{
    [DbContext(typeof(FamilyMeetupDbContext))]
    partial class FamilyMeetupDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.19");

            modelBuilder.Entity("Family_Meetup.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Eventid")
                        .HasColumnType("TEXT");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Eventid");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Family_Meetup.Models.Event", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("creationdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("maxvotesbyuser")
                        .HasColumnType("INTEGER");

                    b.Property<int>("maxvotesondate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("userWhiteList")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Family_Meetup.Models.MeetupDateVoteOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Eventid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("votedusers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Eventid");

                    b.ToTable("MeetupDateVoteOption");
                });

            modelBuilder.Entity("Family_Meetup.Models.Comment", b =>
                {
                    b.HasOne("Family_Meetup.Models.Event", null)
                        .WithMany("comments")
                        .HasForeignKey("Eventid");
                });

            modelBuilder.Entity("Family_Meetup.Models.MeetupDateVoteOption", b =>
                {
                    b.HasOne("Family_Meetup.Models.Event", null)
                        .WithMany("meetupdatevoteoptions")
                        .HasForeignKey("Eventid");
                });

            modelBuilder.Entity("Family_Meetup.Models.Event", b =>
                {
                    b.Navigation("comments");

                    b.Navigation("meetupdatevoteoptions");
                });
#pragma warning restore 612, 618
        }
    }
}
